# Generated by Django 5.2.6 on 2025-09-16 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observer', '0001_initial'),
        ('survey', '0001_initial'),
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveysession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateField(auto_now=True, verbose_name='uploaded_at')),
                ('url', models.CharField(max_length=100)),
                ('number_session', models.CharField(max_length=20)),
                ('start_date', models.DateField(auto_now=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(auto_now=True, verbose_name='end_date')),
                ('observational_distance', models.CharField(max_length=20)),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observer.observer')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.zone')),
            ],
        ),
    ]
