# Generated by Django 5.2.6 on 2025-09-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveysession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysession',
            name='end_date',
            field=models.DateTimeField(verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='surveysession',
            name='start_date',
            field=models.DateField(verbose_name='start_date'),
        ),
    ]
