# Generated by Django 5.2.6 on 2025-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveysession', '0002_alter_surveysession_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysession',
            name='end_date',
            field=models.DateField(verbose_name='end_date'),
        ),
    ]
