# Generated by Django 5.2.6 on 2025-09-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0001_initial'),
        ('survey', '0001_initial'),
        ('surveysession', '0003_alter_surveysession_end_date'),
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='surveysession',
            constraint=models.UniqueConstraint(fields=('survey', 'number_session'), name='unique_number_session_by_survey'),
        ),
    ]
