# Generated by Django 5.2.6 on 2025-10-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveysession', '0004_surveysession_unique_number_session_by_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='visit_number',
            field=models.IntegerField(default=6),
        ),
    ]
