# Generated by Django 5.2.6 on 2025-10-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveysession', '0005_surveysession_visit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
