# Generated by Django 5.2.6 on 2025-09-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
