# Generated by Django 5.2.6 on 2025-09-16 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveysession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.IntegerField()),
                ('visit_date', models.DateField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('complete', models.BooleanField(default=False)),
                ('surveysession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveysession.surveysession')),
            ],
        ),
    ]
