# Generated by Django 5.2.6 on 2025-09-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
