# Generated by Django 5.2.6 on 2025-09-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveysession', '0004_surveysession_unique_number_session_by_survey'),
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('surveysession', 'visit_number'), name='unique_visit_by_surveysession'),
        ),
    ]
