# Generated by Django 5.2.6 on 2025-10-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_visit_unique_visit_by_surveysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(),
        ),
    ]
