# Generated by Django 5.2.6 on 2025-10-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_visit_visit_end_date_alter_visit_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visit_date',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visit_end_date',
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_start_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
