# Generated by Django 5.2.6 on 2025-10-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_remove_visit_end_time_remove_visit_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
