# Generated by Django 5.2.6 on 2025-10-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_alter_visit_visit_start_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='complete',
        ),
        migrations.AddField(
            model_name='visit',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
