# Generated by Django 5.2.6 on 2025-09-19 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
        ('question', '0004_rename_question_parent_id_question_parent_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question.question'),
        ),
    ]
