# Generated by Django 5.2.6 on 2025-09-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0002_alter_option_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
    ]
