# Generated by Django 5.2.6 on 2025-09-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
