# Generated by Django 5.2.6 on 2025-09-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questiontype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=30)),
                ('questiontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questiontype.questiontype')),
            ],
        ),
    ]
