# Generated by Django 5.2.6 on 2025-09-16 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcategory', '0001_initial'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('question_type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('subacategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategory.subcategory')),
                ('survey', models.ManyToManyField(related_name='questions', to='survey.survey')),
            ],
        ),
    ]
