# Generated by Django 5.2.6 on 2025-09-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('subcategory', '0001_initial'),
        ('surveyversion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subacategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategory.subcategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='surveyversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyversion.surveyversion'),
        ),
    ]
