# Generated by Django 5.2.6 on 2025-09-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subacategory',
            new_name='subcategory',
        ),
    ]
