# Generated by Django 5.2.6 on 2025-09-19 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_rename_subacategory_question_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
    ]
