# Generated by Django 5.2.6 on 2025-09-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_question_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_parent_id',
            new_name='parent_question',
        ),
    ]
