# Generated by Django 5.2.6 on 2025-09-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0003_remove_option_question'),
        ('question', '0004_rename_question_parent_id_question_parent_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ptions',
            field=models.ManyToManyField(blank=True, related_name='questions', to='option.option'),
        ),
    ]
