# Generated by Django 5.2.6 on 2025-09-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_question_ptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ptions',
            new_name='options',
        ),
    ]
