# Generated by Django 5.2.6 on 2025-09-16 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('option', '0001_initial'),
        ('question', '0001_initial'),
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.IntegerField(null=True)),
                ('text_value', models.CharField(max_length=30, null=True)),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='option.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.visit')),
            ],
        ),
    ]
