# Generated by Django 5.2.6 on 2025-09-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0003_remove_option_question'),
        ('question', '0006_rename_ptions_question_options'),
        ('response', '0001_initial'),
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('option', 'visita', 'question')},
        ),
    ]
