# Generated by Django 5.2.6 on 2025-09-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0002_initial'),
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='numeric_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='option.option'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text_value',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
