# Generated by Django 5.2.6 on 2025-09-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0003_remove_option_question'),
        ('question', '0006_rename_ptions_question_options'),
        ('response', '0002_alter_response_unique_together'),
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='response',
            name='numeric_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='text_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('visita', 'question'), name='unique_response_by_visita_question_and_option'),
        ),
    ]
