# Generated by Django 5.2.6 on 2025-09-03 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observer', '0001_initial'),
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_uploaded_at', models.DateField(auto_now=True, verbose_name='date_upload')),
                ('url', models.CharField(max_length=200)),
                ('survey_number', models.IntegerField()),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('observational_distance', models.FloatField()),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observer.observer')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.zone')),
            ],
        ),
    ]
