# Generated by Django 5.2.6 on 2025-09-04 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        ('surveyversion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surveyversion.surveyversion'),
        ),
    ]
