# Generated by Django 5.2.6 on 2025-09-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
