# Generated by Django 5.2.6 on 2025-09-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey_survey_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='url_uploaded_at',
            new_name='created_at',
        ),
    ]
