# Generated by Django 5.2.6 on 2025-09-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observer',
            name='telephone',
        ),
    ]
