# Generated by Django 5.2.6 on 2025-09-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observer',
            old_name='phone',
            new_name='telephone',
        ),
    ]
